FROM docker.m.daocloud.io/library/node:20-alpine

RUN npm config set registry https://registry.npmmirror.com && npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile || pnpm install

COPY . .

EXPOSE 5173

CMD ["pnpm", "dev", "--host"]