FROM golang:1.21-alpine

ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on
ENV GOSUMDB=off

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 3000 8080

CMD ["go", "run", "cmd/server/main.go"]